version: "3.8"
services:
  dbn-tools:
    container_name: dbn-tools-container
    image: dbn-tools
    restart: always
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOWNLOAD_URL=${DOWNLOAD_URL}
        - PACKAGE_NAME=${PACKAGE_NAME}
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./downloads:/app/downloads

volumes:
  downloads:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/downloads"
      o: bind
