#!/bin/bash

# Create link symbolic link
ln -s /usr/share/dbn-tools/dbn-tools.sh /usr/bin/dbn-tools

# Create share directory
sudo mkdir /usr/share/dbn-tools

# Copy application to the executable directory
sudo cp ./usr/bin/dbn-tools.sh /usr/share/dbn-tools/dbn-tools.sh

# Give permissions to the application
chmod +x /usr/share/dbn-tools/dbn-tools.sh

# Successfully installed the application, give message to the user
echo "DBN Tools has been installed successfully!"
echo "You can run it by typing 'dbn-tools' in the terminal."