#!/bin/bash

# Create symbolic link
sudo ln -s /usr/share/dbn-tools/usr/bin/dbn-tools.sh /usr/bin/dbn-tools

# Get the project in a more monkey-friendly way
cd /usr/share
git clone -b develop https://github.com/jd-apprentice/dbn-tools.git

# Give permissions to the application and source the files
chmod -R 777 /usr/share/dbn-tools

# Successfully installed the application, give message to the user
echo "DBN Tools has been installed successfully!"
echo "You can run it by typing 'dbn-tools' in the terminal."
